import { defineCompetition } from './schema'

/**
 * Concursos presentados, la mayoría con la plataforma VIA. Sección de índice: no
 * llevan memoria ni ficha propia, sólo datos y una o dos imágenes.
 */
export const competitionSources = [
  defineCompetition({
    slug: 'congress-center-pozuelo',
    title: 'Congress and Exhibition Center',
    location: { es: 'Pozuelo, Madrid', en: 'Pozuelo, Madrid' },
    year: 2024,
    collaboration: 'VIA',
    order: 10,
  }),
  defineCompetition({
    slug: 'mnac-barcelona',
    title: 'National Art Museum of Catalonia',
    location: { es: 'Barcelona', en: 'Barcelona' },
    year: 2024,
    collaboration: 'VIA',
    order: 20,
  }),
  defineCompetition({
    slug: 'royal-cannon-foundry-barcelona',
    title: 'Royal Cannon Foundry Refurbishment',
    location: { es: 'Barcelona', en: 'Barcelona' },
    year: 2023,
    collaboration: 'VIA',
    order: 30,
  }),
  defineCompetition({
    slug: 'udc-research-ferrol',
    title: 'UDC Research Building',
    location: { es: 'Ferrol, Galicia', en: 'Ferrol, Galicia' },
    year: 2023,
    collaboration: 'VIA',
    order: 40,
  }),
  defineCompetition({
    slug: 'cordoba-visitor-center',
    title: 'Cathedral-Mosque Visitor Center',
    location: { es: 'Córdoba', en: 'Córdoba' },
    year: 2022,
    collaboration: 'VIA',
    order: 50,
  }),
  defineCompetition({
    slug: 'sports-complex-leioa',
    title: 'Sports Complex',
    location: { es: 'Leioa, Vizcaya', en: 'Leioa, Biscay' },
    year: 2021,
    collaboration: 'VIA',
    order: 60,
  }),
  defineCompetition({
    slug: 'student-housing-lugano',
    title: 'Student Housing',
    location: { es: 'Lugano, Suiza', en: 'Lugano, Switzerland' },
    year: 2020,
    collaboration: 'VIA',
    order: 70,
  }),
  defineCompetition({
    slug: 'health-sciences-upna',
    title: 'Faculty of Health Sciences UPNA',
    location: { es: 'Pamplona, Navarra', en: 'Pamplona, Navarre' },
    year: 2020,
    collaboration: 'VIA',
    order: 80,
  }),
  defineCompetition({
    slug: 'albaceria-market-barcelona',
    title: 'Albacería Market',
    location: { es: 'Barcelona', en: 'Barcelona' },
    year: 2020,
    collaboration: 'VIA',
    order: 90,
  }),
  defineCompetition({
    slug: 'archaeological-museum-murcia',
    title: 'Archaeological Museum',
    location: { es: 'Murcia', en: 'Murcia' },
    year: 2019,
    collaboration: 'VIA',
    order: 100,
  }),
  defineCompetition({
    slug: 'kultural-center-barcelona',
    title: 'Kultural Center & Book Hub',
    location: { es: 'Barcelona', en: 'Barcelona' },
    year: 2019,
    collaboration: 'VIA',
    order: 110,
  }),
  defineCompetition({
    slug: 'music-center-zelazowa-wola',
    title: 'Music Center',
    location: { es: 'Żelazowa Wola, Polonia', en: 'Żelazowa Wola, Poland' },
    year: 2018,
    collaboration: 'VIA',
    order: 120,
  }),
  defineCompetition({
    slug: 'barcelona-city-archive',
    title: 'Barcelona City Archive',
    location: { es: 'Can Batlló, Barcelona', en: 'Can Batlló, Barcelona' },
    year: 2018,
    collaboration: 'VIA',
    order: 130,
  }),
  defineCompetition({
    slug: 'football-stadium-pamplona',
    title: 'Football Stadium',
    location: { es: 'Pamplona, Navarra', en: 'Pamplona, Navarre' },
    year: 2018,
    collaboration: 'VIA',
    order: 140,
  }),
  defineCompetition({
    slug: 'zamora-easter-museum',
    title: 'Easter Museum',
    location: { es: 'Zamora', en: 'Zamora' },
    year: 2018,
    collaboration: 'VIA',
    order: 150,
  }),
  defineCompetition({
    slug: 'world-car-center-vigo',
    title: 'World Car Center',
    location: { es: 'Vigo, Galicia', en: 'Vigo, Galicia' },
    year: 2018,
    collaboration: 'VIA',
    order: 160,
  }),
  defineCompetition({
    slug: 'health-center-pamplona',
    title: 'Health Center',
    location: { es: 'Pamplona, Navarra', en: 'Pamplona, Navarre' },
    year: 2017,
    collaboration: 'VIA',
    order: 170,
  }),
]
